name: Node with Metrics
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install Dependencies
        run: yarn install
      - name: Run Tests
        run: yarn test
      - name: Release
        run: npx semantic-release
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker Build
        run: |
          docker pull houstonj1/node-with-metrics:latest
          docker build --pull --cache-from houstonj1/node-with-metrics:latest -t houstonj1/node-with-metrics:latest .
      - name: Docker Push
        run: docker push houstonj1/node-with-metrics:latest
